--SSIS Frequently Used Expression
@dtDWDate:					(DT_DATE) ((DT_STR, 10, 1252) SUBSTRING(@[User::strDWDate], 5, 2 ) + "/" +  RIGHT( @[User::strDWDate] , 2)  + "/" +  LEFT( @[User::strDWDate], 4))
@dtDWPrvDate:				DATEADD("dd", -1,  @[User::dtDWDate])
@dtCurrDate:					(DT_DATE) ((DT_STR, 10, 1252) SUBSTRING(@[User::strCurrDate], 5, 2 ) + "/" +  RIGHT( @[User::strCurrDate] , 2)  + "/" +  LEFT( @[User::strCurrDate], 4))
@dtCurrMonthFirstDay:	DATEADD("day",DATEDIFF("day", (DT_DBTIMESTAMP) 0, DATEADD("d",- (DAY(GETDATE())) + 1,GETDATE())),  (DT_DBTIMESTAMP)0)
@dtCurrMonthLastDay:	DATEADD("day",-1,DATEADD("month", 1, @[User::dtCurrMonthFirstDay]))
@dtCurrMonthMidDay:	DATEADD("day",15,@[User::dtCurrMonthFirstDay])
@dtCurrYearFirstDay:		(DT_DATE)(DT_DBDATE)(DATEADD("M",-MONTH(GETDATE())+1,DATEADD("D",-DAY(GETDATE())+1,GETDATE())))
@dtPrvMonthFirstDay:	DATEADD("month",-1,@[User::dtCurrMonthFirstDay])
@dtPrvMonthLastDay: 	DATEADD("day",-1,@[User::dtCurrMonthFirstDay])
@strDWDate:					SUBSTRING((DT_STR,30,1252) DATEADD("dd", -1, GETDATE()),1,4)+SUBSTRING((DT_STR,30,1252) DATEADD("dd", -1, GETDATE()),6,2) +SUBSTRING((DT_STR,30,1252) DATEADD("dd", -1, GETDATE()),9,2)
@strCurrDate:					SUBSTRING((DT_WSTR,30) GETDATE(),1,4)+SUBSTRING((DT_WSTR,30) GETDATE(),6,2) +SUBSTRING((DT_WSTR,30) GETDATE(),9,2)
@dtCurrSaturday:			DATEADD("dd",5,DATEADD("wk",DATEDIFF("wk", (DT_DATE) "01/01/1900",GETDATE()), (DT_DATE) "01/01/1900"))
@dtCurrSunday:				DATEADD("dd",-1,DATEADD("wk",DATEDIFF("wk", (DT_DATE) "01/01/1900",GETDATE()), (DT_DATE) "01/01/1900"))
@dtLastSaturday:			DATEADD("dd",5,DATEADD("wk",DATEDIFF("wk", (DT_DATE) "01/01/1900", DATEADD("dd", -7, GETDATE())), (DT_DATE) "01/01/1900"))
@dtLastSunday:				DATEADD("dd",-1,DATEADD("wk",DATEDIFF("wk", (DT_DATE) "01/01/1900", DATEADD("dd",-7,GETDATE())), (DT_DATE) "01/01/1900"))
@strPrvMonthLastDay:	REPLACE((DT_WSTR, 10)(DT_DBDATE)@dtPrvMonthLastDay,"-","")
